config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :activities
  resources :groups

  root 'splashes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present? # additional permissions for logged in users

    can :manage, Group, user_id: user.id
    can :manage, Activity, author_id: user.id
  end
end

app/models/activities_group.rb
class ActivitiesGroup < ApplicationRecord
  belongs_to :group
  belongs_to :activity
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user, foreign_key: :author_id

  has_many :activities_groups, dependent: :destroy
  has_many :groups, through: :activities_groups, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :activities_groups, dependent: :destroy
  has_many :activities, through: :activities_groups, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :activities, dependent: :destroy, foreign_key: :author_id

  validates :name, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  load_and_authorize_resource
  before_action :set_activity, only: %i[show edit update destroy]

  # GET /activities or /activities.json
  def index
    redirect_to new_activity_path
  end

  # GET /activities/1 or /activities/1.json
  def show; end

  # GET /activities/new
  def new
    @activity = Activity.new
    @groups = current_user.groups
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities or /activities.json
  def create
    @activity = current_user.activities.new(activity_params)

    respond_to do |format|
      if @activity.save
        @activity_group = ActivitiesGroup.create(group_params.merge(activity_id: @activity.id))
        format.html { redirect_to group_path(@activity_group.group_id), notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:name, :amount, :author_id)
  end

  def group_params
    params.require(:activity).permit(:group_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: %i[show]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1 or /groups/1.json
  def show
    @activities = @group.activities.all.order(created_at: :DESC)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create; end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    bootstrap_alert_class = {
      'success' => 'alert-success',
      'error' => 'alert-danger',
      'notice' => 'alert-info',
      'alert' => 'alert-danger',
      'warn' => 'alert-warning'
    }
    bootstrap_alert_class[level]
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def total_amount(activities)
    total_amount = 0
    activities.each do |activity|
      total_amount += activity.amount
    end
    total_amount
  end

  def group_icon(group)
    "https://eu.ui-avatars.com/api/?name=#{group.icon}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/_partials/cards/_activity.html.erb
<div class="card activity-container">
  <div class="g-0 d-flex align-items-center p-2">
        <h3 class="activity-detail">Transaction N°<%= activity.id%></h3>
    <div class="w-50 mx-3">
        <h4 class="activity-body"><%= activity.name %></h5>
    </div>
    <div class="w-50 ml-4 pl-4">
      <h5 class="activity-amount">$ <%= activity.amount %></h4>
    </div>
  </div>
</div>

app/views/_partials/cards/_group.html.erb
<div class="card m-3">
  <div class="g-0 group-card">
    <div class="w-25">
      <img src=<%= group_icon(group)%> alt='icon photo' class='group-icon'>
    </div>
    <div class="w-50 mx-2">
      <div class="card-body">
        <h5 class="group-title display-7 fw-bold"><%= group.name %></h5>
      </div>
      <span class="group-date fs-6"><%= group.created_at.strftime("%d/%m/%Y")%></span>
    </div>
    <div class="w-25 ml-4 pl-4">
      <h4 class="group-total">$ <%= total_amount(group.activities) %></h4>
    </div>
  </div>
</div>

app/views/_partials/cards/_group_header.html.erb
<div class="card w-100 mt-1">
  <div class="g-0 d-flex align-items-center p-2">
    <div class="w-25">
      <img src=<%= group_icon(group)%> alt='icon photo' class='group-icon'>
    </div>
    <div class="w-50 mx-3">
      <div class="card-body">
        <h5 class="display-6 fw-bold text-center"><%= group.name %></h5>
      </div>
    </div>
    <div class="w-25 ml-4 pl-4">
      <h4 class="fw-bold">$ <%= total_amount(activities) %></h4>
    </div>
  </div>
</div>

app/views/_partials/navigations/_navbar.html.erb
<nav class="navbar navbar-dark fixed-top nav-cont">
  <div class="container-fluid align-items-center">
    <% if current_page?(root_path) || current_page?(groups_path) %>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
    <% else %>
      <%= link_to groups_path, class: "back-button" do%>
        <span><img src='https://img.icons8.com/ios-glyphs/24/ffffff/back.png'/></span>
      <% end %>
    <% end %>
    <h4>
    <a class="navbar-brand align-items-center" href="#">Transactor</a>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title text-light" id="offcanvasNavbarLabel">Transactor app</h5>
        <button type="button" class="button-close" data-bs-dismiss="offcanvas" aria-label="Close">X</button>
      </div>
      <div class="offcanvas-body justify-content-center d-flex flex-column">
        <ul class="navbar-nav justify-content-evenly align-items-center flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Groups", groups_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>
   
  

app/views/_partials/navigations/_new_item_button.html.erb
 <%= link_to new_path, class: "new-item-btn btn", id: "add" do%>
    <span><%= label.upcase %></span>
  <% end %>

app/views/activities/_form.html.erb
<div class='add-activity-container d-flex flex-column mt-4 align-items-center'>
  <h1>Add New Activity</h1>

  <%= form_with(model: activity, class: 'add-activity-form d-flex flex-column justify-content-between mt-4') do |form| %>
    <div>
      <% if activity.errors.any? %>
        <div id="error-explanation">
          <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

          <ul>
            <% activity.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.text_field :name, placeholder: 'Name',class: 'input' %>
      </div>

      <div class="field">
        <%= form.text_field :amount, placeholder: 'Amount', class: 'input' %>
      </div>

      <% if @groups.empty? %>
        <p>No groups to show</p>
      <% else %>
        <div class="form-group d-flex flex-column">
          <label for="group" class="form-label display-6 text-center">Pick A Group For Your Activity</label>
          <%= form.select :group_id, @groups.map { |group| [ group.name, group.id]} ,{}, {class: "form-select form-select-lg form-control"} %>
        </div>
      <% end %>

      <%= form.hidden_field :author_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= form.submit 'Save Activity', class: "btn new-item-btn" %>
    </div>
  <% end %>
</div>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<% if user_signed_in? %>

<p id="notice"><%= notice %></p>

  <h1>Activities</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @activities.each do |activity| %>
        <tr>
          <td><%= activity.name %></td>
          <td><%= activity.amount %></td>
          <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Activity', new_activity_path %>

<% else %>
  <div class='recipes-container'>
    <h1>Unauthorized access, please login to continue!</h1>
  </div>
<% end %>

app/views/activities/new.html.erb
<div>
  <%= render 'form', activity: @activity %>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @activity.amount %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/groups/_form.html.erb
<div class='add-group-container d-flex flex-column mt-4 align-items-center'>

  <h1>Add New Group</h1>

  <%= form_with(model: group, class: 'add-activity-form d-flex flex-column justify-content-between mt-4') do |form| %>
    <div>
      <% if group.errors.any? %>
        <div id="error-explanation">
          <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
            <% group.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.text_field :name, placeholder: 'Name',class: 'input' %>
      </div>

      <div class="field">
        <%= form.text_field :icon, placeholder: 'Icon url',class: 'input' %>
      </div>

      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= form.submit 'Save Group', class: "btn new-item-btn" %>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="group-index-container contanier">
  <div class="group-container d-flex flex-column justify-content-between">
    <div class="group-cards text-center">
      <%if @groups.empty? %>
      <h2 class="fw-bold mt-5 display-3">There are no groups</h2>
      <p class="mt-3 display-7">Please add a group with the button bellow</p>
      <%else%>
        <% @groups.each do |group|%>
          <%= link_to group_path(group.id) do%>
            <%= render "_partials/cards/group", group: group %>
          <%end%>
        <%end%>
      <%end%>
      <%= render partial: '_partials/errors/errors' %>
    </div>
    <%= render partial: "_partials/navigations/new_item_button", locals: { label: "Add New Group", new_path: new_group_path } %>
  </div>
</div>

app/views/groups/new.html.erb
<div>
  <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<div class="group-index-container">
  <div class="card">
    <div class="order-container d-flex justify-content-end">
      <p class="text-light fs-6 p-2 bd-highlight">
        Most recent
      </p>
      <p class="text-light fs-6 p-2 bd-highlight">
        Most ancient
      </p>
    </div>
    <div class="card-body d-flex justify-content-between">
      <p class="text fs-5">
        Gift credit
      </p>
      <p class="fs-5">
        $45.00
      </p>
    </div>
  </div>
  <%= render partial: "_partials/cards/group_header", locals: { group: @group, activities: @activities } %>
  <div class="activity-list-container d-flex flex-column justify-content-between mt-4">
    <div class="text-center text-ligth">
      <%if @activities.empty? %>
      <h2 class="fw-bold display-6">No Transactions for this group</h2>
      <p class="mt-3 display-7">Please add activity by clicking the button below</p>
      <%else%>
        <% @activities.each do |activity|%>
            <%= render partial: "_partials/cards/activity", locals: { activity: activity } %>
        <%end%>
      <%end%>
      <%= render partial: '_partials/errors/errors' %>
    </div>
    <%= render partial: "_partials/navigations/new_item_button", locals: { label: "Add Transaction", new_path: new_activity_path } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>

  <body>
    <% if user_signed_in? %> 
      <%= render partial: '_partials/navigations/navbar' %>
      <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
      <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/splashes/index.html.erb
<div class='d-flex flex-column justify-content-center align-items-center splash-container'>
  <div class='splash-wrapper d-flex flex-column justify-content-evenly align-items-center'>
    <h2 class='text-light fw-bold'>TRANSACTOR APP</h2>
    <% if user_signed_in? %>
      <h3 class='text-light'>Welcome, <%= current_user.name.capitalize%></h3>
      <p class='text-light'>You are signed in</p>
      <%= link_to 'Go To Groups', groups_path, class: 'login-btn text-light fw-bold btn mb-4', id: 'go-group' %>
      <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: 'btn btn-light mb-2' %>
    <%else%>
      <%= link_to 'LOG IN', new_user_session_path, class: 'login-btn btn mb-4 py-3 text-light fw-bold' %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn btn-light mb-2 py-3' %>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>